
all: main.cpp Fixed.cpp
	@clear
	c++ -Wall -Wextra -Werror -std=c++98 $^ -o FixPoint_0

run: FixPoint_0
	./FixPoint_0

edit: 
	vi Fixed.cpp

see: 
	less ./Makefile

clean:
	@rm -f ./FixPoint_0
	@rm -f ./a.out
